### ISSUE TITLE
Create a github package for docker image

### ISSUE THREAD

**Issue by freekode** [mrsobakin/dpimyass#3]
As title says. It's just easier to user

**Comment by wzrayyy** [comment]
nah

**Comment by mrsobakin** [comment]
@freekode Okay, here you go. DPIMyAss is now available on my ghcr. See new `docker-compose.yml`.

Please specify image tag version (i.e. `v1.0.0`) if you don't want your service to suddenly break. Config compatibility between versions is not guaranteed.

Thanks for your interest in project.

**Comment by freekode** [comment]
Thanks, appreciate that
